language: java
install: true
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: sotobabi
    token:
      secure: "$SONAR_TOKEN"
script:
- "./gradlew build jacocoTestReport --stacktrace"
- sonar-scanner
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    rooms:
    - codingnomads2019:d1aWT8GvnxhOMXgNmiIHV0eJ#java-travis
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_71f9d37c0817_key -iv $encrypted_71f9d37c0817_iv
  -in secrets/betty-webserver-key.pem.enc -out secrets/betty-webserver-key.pem -d
env:
  global:
  - secure: idmOniLC19rHiEskob6TCR8ESXSYdfwGRIJH4d0SDWLrXiIC8uZcL7/16i6ukjKV2izcS1dLK9plAWCui0kevpjQZIZ6pa09auMynt8sMQjFv5pPGHIJYUTUmM4py8wqiUPIlgLGtHWDCpD9AjoRHQIp7q/eqHpwQYxMMlzV9IT6QfM7+DvX+zSyDXzDRA3cLflqGpH5COhCxjnhqnmC1V7fVc0vfFaAYC5R1eErnKBtCEdCOGZRcgl+Obg1IWCnOQ4oWhxSBU5FUIfpxwhyllfu+nzivD+7ElF++7gcz8h76XwgJStT4eGEtI2ESYcJfdM9LsHIKoDHe6REeUuO1gOhCSuCoS0mSLbrsPAKG3SGRFfgvVCbilpIJbMnV0+Ynq8GWn1cRYFEm4T74jppK840s3u0XH9ahgxi20LX/rdeRWC1L92lmLdrYZGVLoyEnZnVQKR9BogPaUhDTocr7Zp2Yt78UA+lzdXY46lvGrDyPZqrNGSyhQ7O8cx0hCRwVVVLGz3im0UJYXv8h3ZWJucRTFEBTi68wnuOElAEeNV8FzR8BZAfqEZAC6jWmVqaXIu05vfBHIxSfX8zpwMjVsF6uTlCR7uTSc83furOYvOR//KsQWAyklqcG6ziTC4XfVURVBgvx9K8ZZB7xWmXglJRtyyfJJUdSjdRC3AA2QI=
  - secure: b8JmcJi8IMY+IR5RS7MD0k+N8UW1vFTrrvF9zzRfeIUQnSTGd5tU6sRcKUjgRQtqkVLoNJ49s4JP5bhLHWZAVxQ6nQUQmXSCY/DxKaHR78mW7neojbhl0YKROGpwNZ9jYJbPvxQ09QAgYy7ByTaYl1ECHkji69IMSAeSJQwwxgq2OK1s+hwiCmdlX+05Qa23+yqXW3ca4p0qeV9HoIjnj3ERI3DLS9DusbQQMWCMpdJyYvfzgCNJMUSuOlliFx7P4b9P4SSvWs33EVZ/U71R50vzzSVsi8mt0OR8YCp1SQq+K44yqcOIrzZ0Cgl3rLf5Zwjx8ytR569UYPRxmmUtW7zoqY8pB+u53byKwmRdW9CHMCSTjV2wBlbPLlB3eG3GqHSPjpZSQX/tw8U/LqFIEcL3fkN5vdp+Skif1641oAINILxcJf2qJbAO5l/deraV+rB4NCHFjLzw46ICT5yx9biyx+49EmT5uNguBNkATi09yYLRVxjurmNqxu6ppsuVeRdxJxm+XqykDKqRJHNHc+26+jKChqcuf5GzaigOeL0sdOvoqZUfwyAUdsV5NnzSYL6uMFlYfNbiDkNBVpNfSsW6u2seHwcty7UbcoihXMjXfn/qj3mOB+dcV4k2MIynvfgrBHDxwU919rZgmXtXH/gW0g6qi7Ocfrbqnj7Wvgg=
