language: java
install: true
jdk:
- oraclejdk8
script:
- "./gradlew build --stacktrace"
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    rooms:
    - codingnomads2019:d1aWT8GvnxhOMXgNmiIHV0eJ#java-travis
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_71f9d37c0817_key -iv $encrypted_71f9d37c0817_iv
  -in secrets/betty-webserver-key.pem.enc -out secrets/betty-webserver-key.pem -d
